outNetIp:
  39.108.106.167
spring:
  data:
    mongodb:
      uri: mongodb://root:123@${outNetIp}:27017/admin
  application:
    name: user-server
  datasource:
    password: 123
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      max-pool-prepared-statement-per-connection-size: 20
      min-idle: 2
      useGlobalDataSourceStat: true
      max-active: 30
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      filters: wall
      max-wait: 60000
      WebStatFilter:
        exclusions: \*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      StatViewServlet:
        allow: 127.0.0.1
        deny: 192.168.16.111
        loginUsername: admin
        loginPassword: admin
      filter:
        commons-log:
          enabled: true
      test-on-borrow: false
      stat-view-servlet:
        reset-enable: false
      pool-prepared-statements: true
      max-evictable-idle-time-millis: 3000000
      initial-size: 2
      min-evictable-idle-time-millis: 300000
      test-on-return: false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${outNetIp}:3306/ronghui?characterEncoding=utf8&useSSL=false
    username: root
  servlet:
    multipart:
      max-request-size: 10Mb
      max-file-size: 10Mb
  session:
    store-type: redis
  jpa:
    database: MYSQL
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
#  redis:
#    port: 6379
#    host: ${outNetIp}
zimg:
  uri-tmp: https://starfire.site/pic/%s?p=0
server:
  port: 9999
logging:
  level:
    com.alibaba: WARN
    com.ronghui: TRACE
    c.a: WARN
    s.d: WARN
    org.apache: WARN
    org.thymeleaf: WARN
    org.hibernate: ERROR
    org.springframework: WARN
    root: info
    sun: WARN
    o.apache: WARN
